name: Deploy to Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install
      
      - name: Export environment variables
        run: echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> $GITHUB_ENV
        
      - name: Build
        run: npm run build

      - name: Copy Webconfig
        run: cp web.config dist/web.config

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy a App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "konecta-realtimechat-front"
          package: "./dist" 
